'use strict';

const comment = require('../utils/comment')
  , compiler = require('./compile')

  // , BOILERPLATE = fs.readFileSync(path.resolve(__dirname, '../../require.js'), 'utf8')
  , BOILERPLATE = 'if (window.$m == null) window.$m = {};\nif (window.require == null) window.require = function require (id) { return $m[id].exports == null ? $m[id]() : $m[id]; }'
  , HEADER = 'generated by Buddy';

/**
 * Concatenate all 'dependencies' content
 * @param {String} type
 * @param {String} content
 * @param {String} id
 * @param {Array} dependencies
 * @param {Object} options
 * @returns {String}
 */
module.exports = function (type, content, id, dependencies, options) {
  switch (type) {
    case 'js':
      return concatJS(content, id, dependencies, options);
    case 'css':
      return concatCSS(content, options);
    default:
      return content;
  }
};

/**
 * Get concatenated JS 'content'
 * @param {String} content
 * @param {String} id
 * @param {Array} dependencies
 * @param {Object} options
 * @returns {String}
 */
function concatJS (content, id, dependencies, options) {
  const contents = [];

  // Add header comment
  if (options.includeHeader) contents.push(comment(HEADER, 'js'));

  // Add require boilerplate
  contents.push(BOILERPLATE);

  // Add helpers
  if (options.includeHelpers) {
    const helpers = compiler.getHelpers('js');

    if (helpers) contents.push(helpers);
  }

  if (!options.bootstrap) contents.push(`$m['${id}']=function () {`);

  // Add dependencies
  dependencies.filter((dependency) => {
    return dependency.type != 'json';
  }).forEach((dependency) => {
    contents.push(dependency.content);
  });

  contents.push(content);

  if (!options.bootstrap) contents.push(`return $m['${id}'];\n}`);

  return contents.join('\n');
}

/**
 * Get concatenated CSS 'content'
 * @param {String} content
 * @param {Object} options
 * @returns {String}
 */
function concatCSS (content, options) {
  // Add comment
  if (options.includeHeader) content = `${comment(HEADER, 'css')}\n${content}`;

  return content;
}