// Generated by CoffeeScript 1.4.0
var fs, path;

path = require('path');

fs = require('fs');

module.exports = {
  name: 'amd',
  category: 'js',
  type: 'module',
  getModuleID: function(qualifiedFilename) {
    return '';
  },
  getModuleDependencies: function(contents, id) {
    var deps;
    deps = [];
    return deps;
  },
  wrapModuleContents: function(contents, id, isMain) {
    if (isMain == null) {
      isMain = false;
    }
    return contents;
  },
  getModuleFrameworkSource: function() {
    return '';
  }
};
