// Generated by CoffeeScript 1.4.0
var RE_COMMENT_LINES, RE_IMPORT, RE_WIN_SEPARATOR, path;

path = require('path');

RE_WIN_SEPARATOR = /\\\\?/g;

RE_IMPORT = /@import\s['|"](.*?)['|"];?/g;

RE_COMMENT_LINES = /^\s*(?:\/\/|#|\/\*).+(?:\*\/)?$/gm;

module.exports = {
  name: 'css',
  category: 'css',
  type: 'module',
  getModuleID: function(qualifiedFilename) {
    var module;
    module = qualifiedFilename.toLowerCase();
    if (process.platform === 'win32') {
      module = module.replace(RE_WIN_SEPARATOR, '/');
    }
    return module;
  },
  getModuleDependencies: function(content, id) {
    var deps, match;
    deps = [];
    content = content.replace(RE_COMMENT_LINES, '');
    while (match = RE_IMPORT.exec(content)) {
      deps.push(match[1].replace('.css', ''));
    }
    return deps;
  },
  wrapModuleContents: function(content, id) {
    return content;
  },
  concat: function(file) {
    var inline;
    inline = function(file, content) {
      file.dependencies.forEach(function(dependency) {
        var inlineContent, re;
        inlineContent = dependency.dependencies.length ? inline(dependency, dependency.content) : dependency.content;
        re = new RegExp("^@import\\s['|\"]" + dependency.moduleID + "(?:\\.css)?['|\"];?\\s*$", 'im');
        return content = content.replace(re, inlineContent + '\n');
      });
      return content;
    };
    return inline(file, file.content);
  }
};
