// Generated by CoffeeScript 1.4.0
var RE_COMMENT_LINES, RE_IMPORT, RE_SPACES, RE_WIN_SEPARATOR, path;

path = require('path');

RE_WIN_SEPARATOR = /\\\\?/g;

RE_IMPORT = /@import\s['|"](.*?)['|"]/g;

RE_COMMENT_LINES = /^\s*(?:\/\/|#|\/\*).+(?:\*\/)?$/gm;

RE_SPACES = /\s/;

module.exports = {
  name: 'css',
  category: 'css',
  type: 'module',
  getModuleId: function(qualifiedFilename) {
    var module;
    module = qualifiedFilename.toLowerCase().replace(RE_SPACES, '');
    if (process.platform === 'win32') {
      module = module.replace(RE_WIN_SEPARATOR, '/');
    }
    return module;
  },
  getModuleDependencies: function(contents, id) {
    var deps, match;
    deps = [];
    contents = contents.replace(RE_COMMENT_LINES, '');
    while (match = RE_IMPORT.exec(contents)) {
      deps.push(match[1]);
    }
    return deps;
  },
  wrapModuleContents: function(contents, id) {
    return contents;
  },
  inlineDependencies: function(contents, dependencies) {}
};
