// Generated by CoffeeScript 1.4.0
var RE_COMMENT_LINES, RE_MODULE, RE_SPACES, RE_WIN_SEPARATOR, path;

path = require('path');

RE_WIN_SEPARATOR = /\\\\?/g;

RE_MODULE = /^require\.register\(.+function *\( *module *, *exports *, *require *\) *{/gm;

RE_COMMENT_LINES = /^\s*(?:\/\/|#).+$/gm;

RE_SPACES = /\s/;

module.exports = {
  name: 'css',
  category: 'css',
  type: 'module',
  getModuleId: function(qualifiedFilename) {},
  getModuleDependencies: function(contents, id) {},
  wrapModuleContents: function(contents, id) {
    return contents;
  }
};
