// Generated by CoffeeScript 1.4.0
var RE_TRIM, csslint;

csslint = require('csslint').CSSLint;

RE_TRIM = /^\s+|\s+$/;

module.exports = {
  name: 'csslint',
  category: 'css',
  type: 'linter',
  lint: function(data, fn) {
    var items, result;
    result = csslint.verify(data);
    if (result.messages.length) {
      items = result.messages.map(function(error) {
        var _ref;
        return {
          line: error.line,
          col: error.col,
          reason: error.message,
          evidence: (_ref = error.evidence) != null ? _ref.replace(RE_TRIM, '') : void 0
        };
      });
      return fn({
        items: items
      });
    }
  }
};
