// Generated by CoffeeScript 1.4.0
var RE_TRIM, csslint;

csslint = require('csslint').CSSLint;

RE_TRIM = /^\s+|\s+$/;

module.exports = {
	name: 'csslint',
	category: 'css',
	type: 'linter',

	/**
	 * Lint 'data'
	 * @param {String} data
	 * @param {Function} fn(err)
	 */
	lint: function(data, fn) {
		var result = csslint.verify(data);
		if (result.messages.length) {
			var items = result.messages.map(function(error) {
				return {
					line: error.line,
					col: error.col,
					reason: error.message,
					evidence: (error.evidence != null)
						? error.evidence.replace(RE_TRIM, '')
						: null
				};
			});
			fn({items: items});
		}
	}
};
