// Generated by CoffeeScript 1.4.0
var RE_TRIM, jshint;

jshint = require('jshint').JSHINT;

RE_TRIM = /^\s+|\s+$/;

module.exports = {
  name: 'jshint',
  category: 'js',
  type: 'linter',
  options: {
    curly: true,
    eqeqeq: false,
    immed: true,
    latedef: true,
    newcap: true,
    noarg: true,
    undef: true,
    unused: true,
    eqnull: true,
    es5: false,
    esnext: false,
    bitwise: true,
    strict: false,
    trailing: false,
    smarttabs: true,
    node: true,
    boss: true
  },
  lint: function(data, fn) {
    var items, result;
    result = jshint(data, exports.options, {});
    if (!result) {
      items = jshint.errors.map(function(error) {
        var _ref;
        if (error) {
          return {
            line: error.line,
            col: error.character,
            reason: error.reason,
            evidence: (_ref = error.evidence) != null ? _ref.replace(RE_TRIM, '') : void 0
          };
        } else {
          return null;
        }
      });
      return fn({
        items: items
      });
    }
  }
};
