// Generated by CoffeeScript 1.4.0
var Filelog, NAME, RE_ABSOLUTE, existsSync, fs, path;

fs = require('fs');

path = require('path');

existsSync = require('./utils').existsSync;

NAME = '.buddy-filelog';

RE_ABSOLUTE = /^([a-z]:\\)|\//i;

module.exports = Filelog = (function() {

  function Filelog() {
    var json;
    this.filename = path.resolve(NAME);
    this.files = existsSync(this.filename) ? JSON.parse(json = fs.readFileSync(this.filename, 'utf8')) : [];
    if (this.files.length) {
      if ((path.sep === '/' && json.indexOf('\\') !== -1) || (path.sep === '\\' && json.indexOf('/') !== -1) || RE_ABSOLUTE.test(this.files[0])) {
        this.clean();
      }
    }
  }

  Filelog.prototype.add = function(files) {
    var _this = this;
    files.forEach(function(file) {
      file = path.relative(process.cwd(), file);
      if (_this.files.indexOf(file) === -1) {
        return _this.files.push(file);
      }
    });
    return fs.writeFileSync(this.filename, JSON.stringify(this.files));
  };

  Filelog.prototype.clean = function() {
    this.files = [];
    return fs.writeFileSync(this.filename, JSON.stringify(this.files), 'utf8');
  };

  return Filelog;

})();
