// Generated by CoffeeScript 1.4.0
var Filelog, NAME, existsSync, fs, path;

fs = require('fs');

path = require('path');

existsSync = fs.existsSync || path.existsSync;

NAME = '.buddy-filelog';

module.exports = Filelog = (function() {

  function Filelog() {
    this.filename = path.resolve(NAME);
    this.files = existsSync(this.filename) ? JSON.parse(fs.readFileSync(this.filename, 'utf8')) : [];
  }

  Filelog.prototype.add = function(files) {
    var _this = this;
    files.forEach(function(file) {
      file = path.relative(process.cwd(), file);
      if (_this.files.indexOf(file) === -1) {
        return _this.files.push(file);
      }
    });
    return fs.writeFileSync(this.filename, JSON.stringify(this.files));
  };

  Filelog.prototype.clean = function() {
    this.files = [];
    return fs.writeFileSync(this.filename, JSON.stringify(this.files), 'utf8');
  };

  return Filelog;

})();
