// Generated by CoffeeScript 1.4.0
var RE_IGNORE, cp, exists, existsSync, fs, mkdir, mkdirp, mv, notify, path, readdir, rimraf, rm;

fs = require('fs');

path = require('path');

mkdirp = require('mkdirp');

rimraf = require('rimraf');

exports.existsSync = existsSync = fs.existsSync || path.existsSync;

exports.exists = exists = fs.exists || path.exists;

RE_IGNORE = /^[\.~]|~$/;

exports.notify = notify = {
  RED: '0;31',
  YELLOW: '1;33',
  GREEN: '0;32',
  GREY: '0;90',
  silent: false,
  nocolor: !process.stdout.isTTY,
  colour: function(string, colourCode) {
    if (this.nocolor) {
      return string;
    } else {
      return '\033[' + colourCode + 'm' + string + '\033[0m';
    }
  },
  print: function(msg, ind) {
    if (ind == null) {
      ind = 1;
    }
    if (!this.silent) {
      return console.log(exports.indent(msg, ind));
    }
  },
  error: function(err, ind) {
    if (ind == null) {
      ind = 1;
    }
    if ('string' === typeof err) {
      err = new Error(err);
    }
    this.print("" + (this.colour('error', this.RED)) + ": " + err.message, ind);
    throw err;
  },
  warn: function(msg, indent) {
    if (indent == null) {
      indent = 1;
    }
    return this.print("" + (this.colour('warning', this.YELLOW)) + " " + msg, indent);
  },
  strong: function(string) {
    return this.colour(string, this.GREY);
  }
};

exports.readdir = readdir = function(dir, fn, ignore) {
  var _files, _outstanding, _readdir;
  ignore = ignore ? new RegExp(RE_IGNORE.source + '|' + ignore.source) : RE_IGNORE;
  _outstanding = 0;
  _files = [];
  _readdir = function(dir) {
    _outstanding++;
    return fs.readdir(dir, function(err, files) {
      _outstanding--;
      if (err) {
        if (err.code === 'ENOENT') {

        } else {
          return fn(err);
        }
      } else {
        files.forEach(function(file) {
          var filepath;
          if (!ignore.test(path.basename(file))) {
            filepath = path.resolve(dir, file);
            _outstanding++;
            return fs.stat(filepath, function(err, stats) {
              _outstanding--;
              if (err) {
                if (err.code === 'ENOENT') {

                } else {
                  return fn(err);
                }
              } else {
                if (stats.isDirectory()) {
                  return _readdir(filepath);
                } else {
                  _files.push(filepath);
                  if (!_outstanding) {
                    return fn(null, _files);
                  }
                }
              }
            });
          }
        });
        if (!_outstanding) {
          return fn(null, _files);
        }
      }
    });
  };
  return _readdir(dir);
};

exports.mkdir = mkdir = function(filepath, fn) {
  var dir;
  dir = path.extname(filepath) ? path.dirname(filepath) : filepath;
  if (!existsSync(dir)) {
    return mkdirp(dir, function(err) {
      if (err) {
        return fn(err);
      } else {
        return fn();
      }
    });
  } else {
    return fn();
  }
};

exports.mv = mv = function(source, destination, fn) {
  return mkdir(destination, function(err) {
    var filepath;
    if (err) {
      return fn(err);
    } else {
      filepath = path.resolve(destination, path.basename(source));
      if (existsSync(filepath)) {
        return fn(new Error('already exists: ' + filepath));
      } else {
        return fs.rename(source, filepath, function(err) {
          if (err) {
            return fn(err);
          } else {
            return fn(null, filepath);
          }
        });
      }
    }
  });
};

exports.cp = cp = function(source, destination) {
  var base, contentsOnly, dir, filename, _base, _cp, _outstanding,
    _this = this;
  _outstanding = 0;
  _base = _cp = function(source, destination) {};
  if (fs.statSync(source).isFile()) {
    if (path.dirname(source) === path.dirname(destination)) {
      if (path.basename(destination) && path.basename(destination) !== path.basename(source)) {
        filename = destination;
      } else {
        filename = source.replace('.', ' copy.');
      }
    } else {
      filename = path.resolve(destination, path.basename(source));
    }
    if (!existsSync(filename)) {
      fs.writeFileSync(filename, fs.readFileSync(source));
    }
    return filename;
  } else {
    contentsOnly = source.charAt(source.length - 1) === '/' && !base ? true : false;
    base = contentsOnly ? path.resolve(source) : path.dirname(path.resolve(source));
    dir = path.resolve(destination, source.replace(base, destination));
    mkdir(dir);
    fs.readdirSync(source).forEach(function(item) {
      return cp(path.resolve(source, item), dir, base);
    });
    return dir;
  }
};

exports.rm = rm = function(source, fn) {
  if (existsSync(source)) {
    if (source.indexOf(process.cwd()) !== -1) {
      return rimraf(source, function(err) {
        if (err) {
          return fn(err);
        } else {
          return fn();
        }
      });
    } else {
      return fn(new Error('cannot rm source outside of project path: ' + source));
    }
  } else {
    return fn(new Error('cannot rm non-existant source: ' + source));
  }
};

exports.indent = function(string, level) {
  var re;
  re = /^/gm;
  string = string.replace(re, (new Array(level)).join('  '));
  return string;
};

exports.wait = function(time, fn) {
  if (time == null) {
    time = 25;
  }
  return setTimeout(fn, time);
};
