// Generated by CoffeeScript 1.4.0
var Watcher, existsSync, fs, path, wait;

fs = require('fs');

path = require('path');

wait = require('./utils').wait;

existsSync = fs.existsSync || path.existsSync;

module.exports = Watcher = (function() {

  function Watcher(source, ignore, fn) {
    var watcher;
    this.source = source;
    this.ignore = ignore;
    watcher = fs.watch(this.source, function() {});
  }

  return Watcher;

})();
