// Generated by CoffeeScript 1.4.0
var coffee;

coffee = require('coffee-script');

module.exports = {
  name: 'coffeescript',
  extension: 'coffee',
  category: 'js',
  type: 'compiler',
  compile: function(data, fn) {
    var compiled;
    try {
      compiled = coffee.compile(data, {
        bare: true
      });
      return fn(null, compiled);
    } catch (err) {
      return fn(err, '');
    }
  }
};
