// Generated by CoffeeScript 1.4.0
var stylus;

stylus = require('stylus');

module.exports = {
  name: 'stylus',
  extension: 'styl',
  category: 'css',
  type: 'compiler',
  compile: function(content, fn) {
    var stylc,
      _this = this;
    stylc = stylus(content).set('paths', sources);
    return stylc.render(function(err, css) {
      if (err) {
        return fn(err, '');
      } else {
        return fn(null, css);
      }
    });
  }
};
