// Generated by CoffeeScript 1.4.0
var cleanCSS;

cleanCSS = require('clean-css');

module.exports = {
  name: 'cleancss',
  category: 'css',
  type: 'compressor',
  compress: function(data, fn) {
    var compressed;
    try {
      compressed = cleanCSS.process(data);
      return fn(null, compressed);
    } catch (err) {
      return fn(err);
    }
  }
};
