// Generated by CoffeeScript 1.4.0
var uglify;

uglify = require('uglify-js');

module.exports = {
  name: 'uglifyjs',
  category: 'js',
  type: 'compressor',
  compress: function(data, fn) {
    var ast, compressed, jsp, pro;
    try {
      jsp = uglify.parser;
      pro = uglify.uglify;
      ast = jsp.parse(data);
      ast = pro.ast_mangle(ast);
      ast = pro.ast_squeeze(ast);
      compressed = pro.gen_code(ast);
      return fn(null, compressed);
    } catch (err) {
      return fn(err);
    }
  }
};
