// Generated by CoffeeScript 1.4.0
var uglify;

uglify = require('uglify-js');

module.exports = {
  name: 'uglifyjs',
  category: 'js',
  type: 'compressor',
  compress: function(data, fn) {
    var result;
    try {
      result = uglify.minify(data, {
        fromString: true
      });
      return fn(null, result.code);
    } catch (err) {
      return fn(err);
    }
  }
};
