// Generated by CoffeeScript 1.4.0
var DEFAULT, DEFAULT_JSON, debug, existsSync, fs, locate, path, strong, _ref;

fs = require('fs');

path = require('path');

existsSync = require('../utils/fs').existsSync;

_ref = require('../utils/notify'), debug = _ref.debug, strong = _ref.strong;

DEFAULT = 'buddy.js';

DEFAULT_JSON = 'buddy.json';

exports.data = null;

exports.url = '';

exports.load = function(url, fn) {
  debug('CONFIGURATION', 1);
  return locate(url, function(err) {
    var data;
    if (err) {
      return fn(err);
    }
    try {
      data = require(exports.url);
    } catch (err) {
      return fn("parsing " + (strong(exports.url)) + "\n  Run " + (strong('buddy -h')) + " for proper formatting");
    }
    if (data.build || data.dependencies || data.settings) {
      exports.data = data;
      process.chdir(path.dirname(exports.url));
      return fn(null, data);
    } else {
      return fn("parsing " + (strong(exports.url)) + "\n  Run " + (strong('buddy -h')) + " for proper formatting");
    }
  });
};

exports.locate = locate = function(url, fn) {
  var dir, parent, urljs, urljson;
  if (url) {
    url = path.resolve(url);
    if (existsSync(url)) {
      return fs.stat(url, function(err, stats) {
        var urljs, urljson;
        if (err) {
          return fn(err);
        }
        if (!path.extname(url).length || stats.isDirectory()) {
          urljs = path.join(url, DEFAULT);
          urljson = path.join(url, DEFAULT_JSON);
          if (existsSync(url = urljs) || existsSync(url = urljson)) {
            debug("config file found at: " + (strong(url)), 2);
            exports.url = url;
            return fn(null, url);
          } else {
            return fn("" + (strong(path.basename(url))) + " not found in " + (strong(path.dirname(url))));
          }
        } else {
          debug("config file found at: " + (strong(url)), 2);
          exports.url = url;
          return fn(null, url);
        }
      });
    } else {
      return fn("" + (strong(path.basename(url))) + " not found in " + (strong(path.dirname(url))));
    }
  } else {
    while (true) {
      if (typeof dir !== "undefined" && dir !== null) {
        parent = path.resolve(dir, '../');
        if (parent === dir) {
          return fn("" + (strong(DEFAULT)) + " not found on this path");
        } else {
          dir = parent;
        }
      } else {
        dir = process.cwd();
      }
      urljs = path.join(dir, DEFAULT);
      urljson = path.join(dir, DEFAULT_JSON);
      if (existsSync(url = urljs) || existsSync(url = urljson)) {
        debug("config file found at: " + (strong(url)), 2);
        exports.url = url;
        return fn(null);
      }
    }
  }
};
