// Generated by CoffeeScript 1.4.0
var CSSFile, File,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

File = require('./file');

module.exports = CSSFile = (function(_super) {

  __extends(CSSFile, _super);

  function CSSFile(filepath, basepath, compilers) {
    CSSFile.__super__.constructor.call(this, 'css', filepath, basepath, compilers);
  }

  CSSFile.prototype.parseContents = function(modular, fn) {
    var _this = this;
    return CSSFile.__super__.parseContents.call(this, function(err, data) {
      if (err) {
        return fn(err);
      }
      return fn(null, data);
    });
  };

  return CSSFile;

})(File);
