// Generated by CoffeeScript 1.4.0
var File, Source, existsSync, path, readdir, _ref,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

path = require('path');

File = require('./file');

_ref = require('../utils/utils'), readdir = _ref.readdir, existsSync = _ref.existsSync;

module.exports = Source = (function() {

  function Source(type, sources) {
    var _this = this;
    this.type = type;
    this._onWatchDelete = __bind(this._onWatchDelete, this);

    this._onWatchChange = __bind(this._onWatchChange, this);

    this._onWatchCreate = __bind(this._onWatchCreate, this);

    ({
      this.byPath: {},
      this.byModule: {},
      this.length: 0
    });
    this.locations = [];
    sources.forEach(function(source) {
      return _this.locations.push(path.resolve(source));
    });
  }

  Source.prototype.parse = function(ignore, fn) {
    var outstanding,
      _this = this;
    outstanding = 0;
    return this.locations.forEach(function(location) {
      outstanding++;
      return readdir(location, ignore, function(err, files) {
        outstanding--;
        if (err) {
          return fn(err);
        }
        files.forEach(function(file) {
          return _this.add(file);
        });
        if (!outstanding) {
          return fn();
        }
      });
    });
  };

  Source.prototype.add = function(file) {
    this.length++;
    this.byPath[file.filepath] = file;
    return this.byModule[file.moduleId] = file;
  };

  Source.prototype.remove = function(file) {
    this.length--;
    delete this.byPath[file.filepath];
    delete this.byModule[file.moduleId];
    return file.destroy();
  };

  Source.prototype.watch = function(fn) {};

  Source.prototype._onWatchCreate = function(filename, stats) {
    var file, type;
    type = this._getFileType(filename);
    if (type && (file = this._fileFactory(filename, this._getSourceLocation(filename, type)))) {
      notify.print("[" + (new Date().toLocaleTimeString()) + "] " + (notify.colour('added', notify.GREEN)) + " " + (notify.strong(path.basename(filename))), 3);
      return this._cacheFile(file, this[type + 'Sources']);
    }
  };

  Source.prototype._onWatchChange = function(filename, stats) {
    var type,
      _this = this;
    notify.print("[" + (new Date().toLocaleTimeString()) + "] " + (notify.colour('changed', notify.YELLOW)) + " " + (notify.strong(path.basename(filename))), 3);
    type = this._getFileType(filename);
    return this[type + 'Targets'].forEach(function(target) {
      target.watching = true;
      return _this._runTarget(target, _this.compress, false);
    });
  };

  Source.prototype._onWatchDelete = function(filename) {
    var file, type;
    type = this._getFileType(filename);
    if (type && (file = this[type + 'Sources'].byPath[filename])) {
      notify.print("[" + (new Date().toLocaleTimeString()) + "] " + (notify.colour('removed', notify.RED)) + " " + (notify.strong(path.basename(filename))), 3);
      return this._uncacheFile(file, this[type + 'Sources']);
    }
  };

  return Source;

})();
