// Generated by CoffeeScript 1.4.0
var NAME, RE_ABSOLUTE, clean, existsSync, filename, files, fs, path;

fs = require('fs');

path = require('path');

existsSync = require('./fs').existsSync;

NAME = '.buddy-filelog';

RE_ABSOLUTE = /^([a-z]:\\)|^\//i;

exports.filename = filename = path.resolve(NAME);

exports.files = files = [];

if (existsSync(filename)) {
  fs.readFile(filename, 'utf8', function(err, data) {
    if (err) {
      return;
    }
    try {
      files = JSON.parse(data);
      if (files.length) {
        if ((path.sep === '/' && data.indexOf('\\') !== -1) || (path.sep === '\\' && data.indexOf('/') !== -1) || RE_ABSOLUTE.test(files[0])) {
          return clean();
        }
      }
    } catch (err) {

    }
  });
}

exports.add = function(newFiles, fn) {
  var _this = this;
  newFiles.forEach(function(file) {
    file = path.relative(process.cwd(), file);
    if (files.indexOf(file) === -1) {
      return files.push(file);
    }
  });
  return fs.writeFile(filename, JSON.stringify(files), 'utf8', function(err) {
    if (err) {
      return fn(err);
    } else {
      return fn(null, files);
    }
  });
};

exports.clean = clean = function(fn) {
  files = [];
  return fs.writeFile(filename, JSON.stringify(files), 'utf8', function(err) {
    if (err) {
      return fn(err);
    } else {
      return fn();
    }
  });
};
