// Generated by CoffeeScript 1.4.0

exports.RED = '0;31';

exports.YELLOW = '1;33';

exports.CYAN = '1;36';

exports.GREEN = '0;32';

exports.GREY = '0;90';

exports.silent = false;

exports.verbose = false;

exports.nocolor = !process.stdout.isTTY;

exports.start = 0;

exports.colour = function(string, colourCode) {
  if (exports.nocolor) {
    return string;
  } else {
    return '\033[' + colourCode + 'm' + string + '\033[0m';
  }
};

exports.print = function(msg, column) {
  if (column == null) {
    column = 0;
  }
  if (!exports.silent) {
    return console.log(exports.indent(msg, column));
  }
};

exports.error = function(err, column) {
  if (column == null) {
    column = 0;
  }
  if ('string' === typeof err) {
    err = new Error(err);
  }
  exports.print("" + (exports.colour('error', exports.RED)) + ": " + err.message, column);
  throw err;
};

exports.warn = function(msg, column) {
  if (column == null) {
    column = 0;
  }
  if ('string' instanceof Error) {
    msg = msg.message;
  }
  return exports.print("" + (exports.colour('warning', exports.YELLOW)) + " " + msg, column);
};

exports.debug = function(msg, column) {
  if (column == null) {
    column = 0;
  }
  if (exports.verbose) {
    return exports.print("" + (exports.colour('+', exports.CYAN)) + (exports.strong(+(new Date) - exports.start + 'ms')) + (exports.colour('::', exports.CYAN)) + msg, column);
  }
};

exports.strong = function(string) {
  return exports.colour(string, exports.GREY);
};

exports.indent = function(string, column) {
  var spaces;
  spaces = (new Array(column)).join('  ');
  return string.replace(/^/gm, spaces);
};
