// Generated by CoffeeScript 1.4.0

exports.RED = '0;31';

exports.YELLOW = '1;33';

exports.CYAN = '1;36';

exports.GREEN = '0;32';

exports.GREY = '0;90';

exports.silent = false;

exports.verbose = false;

exports.nocolor = !process.stdout.isTTY;

exports.start = exports.last = 0;

exports.colour = function(string, colourCode) {
  if (exports.nocolor) {
    return string;
  } else {
    return '\033[' + colourCode + 'm' + string + '\033[0m';
  }
};

exports.print = function(msg, column) {
  if (column == null) {
    column = 0;
  }
  if (!exports.silent) {
    return console.log(exports.indent(msg, column));
  }
};

exports.error = function(err, column, throws) {
  if (column == null) {
    column = 0;
  }
  if (throws == null) {
    throws = true;
  }
  if ('string' === typeof err) {
    err = new Error(err);
  }
  if (!throws) {
    err.message += '\x07';
  }
  exports.print("" + (exports.colour('error', exports.RED)) + ": " + err.message, column);
  if (throws) {
    throw err;
  }
};

exports.warn = function(msg, column) {
  if (column == null) {
    column = 0;
  }
  if ('string' instanceof Error) {
    msg = msg.message;
  }
  return exports.print("" + (exports.colour('warning', exports.YELLOW)) + " " + msg, column);
};

exports.debug = function(msg, column) {
  var now;
  if (column == null) {
    column = 0;
  }
  now = +(new Date);
  if (!exports.last) {
    exports.last = exports.start;
  }
  if (exports.verbose) {
    exports.print("" + (exports.colour('+', exports.CYAN)) + (exports.strong(now - exports.last + 'ms')) + (exports.colour('::', exports.CYAN)) + (exports.strong(now - exports.start + 'ms')) + (exports.colour('=', exports.CYAN)) + msg, column);
  }
  return exports.last = now;
};

exports.strong = function(string) {
  return exports.colour(string, exports.GREY);
};

exports.indent = function(string, column) {
  var spaces;
  spaces = (new Array(column)).join('  ');
  return string.replace(/^/gm, spaces);
};
