// Generated by CoffeeScript 1.4.0

exports.RED = '0;31';

exports.YELLOW = '1;33';

exports.GREEN = '0;32';

exports.GREY = '0;90';

exports.silent = false;

exports.nocolor = !process.stdout.isTTY;

exports.colour = function(string, colourCode) {
  if (exports.nocolor) {
    return string;
  } else {
    return '\033[' + colourCode + 'm' + string + '\033[0m';
  }
};

exports.print = function(msg, ind) {
  if (ind == null) {
    ind = 1;
  }
  if (!exports.silent) {
    return console.log(exports.indent(msg, ind));
  }
};

exports.error = function(err, ind) {
  if (ind == null) {
    ind = 1;
  }
  if ('string' === typeof err) {
    err = new Error(err);
  }
  exports.print("" + (exports.colour('error', exports.RED)) + ": " + err.message, ind);
  throw err;
};

exports.warn = function(msg, indent) {
  if (indent == null) {
    indent = 1;
  }
  if ('string' instanceof Error) {
    msg = msg.message;
  }
  return exports.print("" + (exports.colour('warning', exports.YELLOW)) + " " + msg, indent);
};

exports.strong = function(string) {
  return exports.colour(string, exports.GREY);
};

exports.indent = function(string, column) {
  var spaces;
  spaces = (new Array(column)).join('  ');
  return string.replace(/^/gm, spaces);
};
