// Generated by CoffeeScript 1.4.0
var ReloadServer, debug, fs, path, ready, server, strong, _ref;

path = require('path');

fs = require('fs');

ReloadServer = require('./reloadserver');

_ref = require('./notify'), debug = _ref.debug, strong = _ref.strong;

server = null;

ready = false;

exports.start = function() {
  if (!server) {
    server = new ReloadServer();
    server.on('connected', function(connection) {
      return debug("live-reload client connected: " + connection.id, 4);
    });
    server.on('disconnected', function(connection) {
      return debug("live-reload client disconnected: " + connection.id, 4);
    });
    server.on('command', function(message) {
      return debug("received live-reload command '" + message.command + "': " + message.url, 4);
    });
    server.on('error', function(err) {
      return fn(err);
    });
    return server.listen(function(err) {
      if (!err) {
        debug("started live-reload server on port: " + server.port, 3);
        return ready = true;
      }
    });
  }
};

exports.stop = function() {
  if (server) {
    server.close();
    server = null;
    return ready = false;
  }
};

exports.refresh = function(file) {
  var msg;
  if (ready) {
    msg = {
      command: 'reload',
      path: file,
      liveCSS: true
    };
    debug("sending " + (strong('reload')) + " command to live-reload clients", 4);
    return server.activeConnections().forEach(function(connection) {
      return connection.send(msg);
    });
  }
};
