// Generated by CoffeeScript 1.4.0
var notify;

exports.notify = notify = {
  RED: '0;31',
  YELLOW: '1;33',
  GREEN: '0;32',
  GREY: '0;90',
  silent: false,
  nocolor: !process.stdout.isTTY,
  colour: function(string, colourCode) {
    if (this.nocolor) {
      return string;
    } else {
      return '\033[' + colourCode + 'm' + string + '\033[0m';
    }
  },
  print: function(msg, ind) {
    if (ind == null) {
      ind = 1;
    }
    if (!this.silent) {
      return console.log(exports.indent(msg, ind));
    }
  },
  error: function(err, ind) {
    if (ind == null) {
      ind = 1;
    }
    if ('string' === typeof err) {
      err = new Error(err);
    }
    this.print("" + (this.colour('error', this.RED)) + ": " + err.message, ind);
    throw err;
  },
  warn: function(msg, indent) {
    if (indent == null) {
      indent = 1;
    }
    if ('string' instanceof Error) {
      msg = msg.message;
    }
    return this.print("" + (this.colour('warning', this.YELLOW)) + " " + msg, indent);
  },
  strong: function(string) {
    return this.colour(string, this.GREY);
  }
};

exports.indent = function(string, level) {
  var re;
  re = /^/gm;
  string = string.replace(re, (new Array(level)).join('  '));
  return string;
};
