// Generated by CoffeeScript 1.4.0
var less;

less = require('less');

module.exports = {
  name: 'less',
  extension: 'less',
  category: 'css',
  type: 'compiler',
  compile: function(data, sources, fn) {
    var parser,
      _this = this;
    parser = new less.Parser({
      paths: sources
    });
    return parser.parse(data, function(err, tree) {
      if (err) {
        return fn(err, '');
      } else {
        return fn(null, tree.toCSS());
      }
    });
  }
};
