// Generated by CoffeeScript 1.4.0
var csslint, path;

path = require('path');

csslint = require('csslint').CSSLint;

module.exports = {
  name: 'csslint',
  category: 'css',
  type: 'linter',
  lint: function(data, fn) {
    var items, result;
    result = csslint.verify(data);
    if (result.messages.length) {
      items = result.messages.map(function(error) {
        return {
          line: error.line,
          col: error.col,
          reason: error.message
        };
      });
      return fn({
        items: items
      });
    }
  }
};
